name: dot_tab_indicator
description: Customizable Dot Tab Indicator.
version: 1.0.0+nnbd
author: Jaroslaw Butajlo <jaroslaw.butajlo(at)gmail.com>
homepage: https://github.com/jarekb123/dot_tab_indicator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

